// <auto-generated />
using System;
using FitForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitForgeDbContext))]
    partial class FitForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitForge.Domain.Members.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<byte>("Experience")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Goal")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("UTC");

                    b.Property<byte>("Units")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_Member_NormalizedEmail");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Member_PublicId");

                    b.ToTable("Member", null, t =>
                        {
                            t.HasCheckConstraint("CK_Member_Experience", "[Experience] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_Member_Goal", "[Goal] BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_Member_Units", "[Units] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("FitForge.Domain.Members.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Profile_MemberId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Profile_PublicId");

                    b.ToTable("Profile", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profile_BirthYear", "[BirthYear] IS NULL OR [BirthYear] BETWEEN 1900 AND 2200");

                            t.HasCheckConstraint("CK_Profile_HeightCm", "[HeightCm] IS NULL OR [HeightCm] > 0");

                            t.HasCheckConstraint("CK_Profile_Sex", "[Sex] IS NULL OR [Sex] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("FitForge.Domain.Members.Profile", b =>
                {
                    b.HasOne("FitForge.Domain.Members.Member", "Member")
                        .WithOne("Profile")
                        .HasForeignKey("FitForge.Domain.Members.Profile", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Profile_Member");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitForge.Domain.Members.Member", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
